categories/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [url(r'^homepage/$', views.homepage, name='homepage'),
               url(r'^computer-science/$', views.cs, name='cs'),
               url(r'^business/$', views.business, name='business'),
               url(r'^astronomy/$', views.astronomy, name='astronomy'),
               url(r'^homepage-search$', views.searchHome, name='homepageS'),
               url(r'^computer-science-search$', views.searchCs, name='csS'),
               url(r'^business-search$', views.searchBusiness, name='businessS'),
               url(r'^astronomy-search$', views.searchAstronomy, name='astronomyS')]

know_it_all/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('signIn.urls', namespace="sign_in")),
    url(r'^categories/', include('categories.urls', namespace="categories")),
    url(r'^reader/', include('reader.urls', namespace="reader")),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout')
]

reader/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [url(r'^upload/$', views.upload, name='upload')]

signIn/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [url(r'^register/$', views.register, name='register'),
               url(r'^$', views.signInBeta, name='profile')]

categories/models.py
from django.db import models

# Create your models here.

signIn/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    profile_pic = models.FileField(upload_to="profile pics/")

    def __str__(self):
        return self.first_name + ' ' + self.last_name

categories/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class Register(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class ProfileInfo(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'level']

categories/views.py
from django.shortcuts import render
from reader.searchEngine import stripQuery, getMeaning, getCourses
# Create your views here.


def homepage(request):
	return render(request, 'homepage.html')


def cs(request):
	return render(request, 'computer-science.html')


def business(request):
	return render(request, 'business.html')


def astronomy(request):
	return render(request, 'astronomy.html')


def search(request, domain, showDomain=False):
	if request.method == 'POST':
		search_query = str(request.POST.get('srch'))
		domainActual = str(request.POST.get('dom'))

		if domainActual == "False":
			showDomain = False

		print(search_query)

		query = stripQuery(search_query)
		meaning = getMeaning(query, search_query)
		courses = getCourses(query, domain=domainActual, showDomain=showDomain)
		results = {}
		results['meaning'] = meaning
		results['courses'] = courses

		print(meaning)

		if domain == "homepage":
			return render(request, 'search.html', results)
		else:
			return render(request, 'searchResult.html', results)
	else:
		return render(request, domain + '.html')


def searchCs(request):
	return search(request, 'computer-science', True)


def searchBusiness(request):
	return search(request, 'business', True)


def searchAstronomy(request):
	return search(request, 'astronomy')


def searchHome(request):
	return search(request, 'homepage', showDomain=True)

reader/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
from .pdfToJrg import getResultTuple
from .searchEngine import getMeaning, stripQuery
# Create your views here.


def upload(request):
	if request.method == 'POST' and request.FILES['myfile']:
		myfile = request.FILES['myfile']
		fs = FileSystemStorage()
		fs.save('reader/pdfDoc/' + myfile.name, myfile)
		textString, jargon = getResultTuple(myfile.name)
		readerDict = {}
		readerDict['text'] = textString
		readerDict['jargon'] = jargon
		readerDict['meaning'] = [getMeaning(stripQuery(i), i) for i in jargon]
		return render(request, 'reader.html', readerDict)
	else:
		return render(request, 'upload.html')

signIn/views.py
from django.shortcuts import render, redirect
from .forms import Register, ProfileInfo
from django.contrib.auth import authenticate, login
from .models import Profile
# from forum.models import Post


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = Register(request.POST)
        profile_form = ProfileInfo(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password')

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            login(request, authenticate(username=username, password=raw_password))
            registered = True
    else:
        user_form = Register(request.POST)
        profile_form = ProfileInfo(request.POST, request.FILES)
    if registered:
        return redirect('/booklisting/search/')
    else:
        return render(request, 'sign_in/register.html', {'user_form': user_form, 'profile_form': profile_form})


def profile(request):
    user = Profile.objects.get(user=request.user)
    # post = Post.objects.filter(user=request.user)
    # return render(request, 'sign_in/profile.html', {'user': user, 'forum': post})
    return render(request, 'sign_in/profile.html', {'user': user})


def signInBeta(request):
	return render(request, 'sign_in/signin.html')

categories/templates/astronomy.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="/static/css/landing-page.min.css" rel="stylesheet">

  </head>

  <body >

    <!-- Navigation -->
    <div style="background:black;">
    <nav class="navbar navbar-light  static-top" >
      <div class="container">
        <a class="navbar-brand" href="#" style="color:white;">ASTRONOMY</a>
        <a class="btn btn-primary" href="#">Search</a>
      </div>
    </nav>
  </div>

    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Know It All Right Here!</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="text" class="form-control form-control-lg" placeholder="Enter your word">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
 <!--   <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Fully Responsive</h3>
              <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
              </div>
              <h3>Bootstrap 4 Ready</h3>
              <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h3>Easy to Use</h3>
              <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
            </div>
          </div>
        </div>
      </div>
    </section> -->

    <!-- Image Showcases -->
    <section class="showcase" style="text-align:center"> 
      <div class="container-fluid p-0">
        <div class="row no-gutters">

       <!--   <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.jpg');"></div> -->
          <div class="col-lg-6 order-lg-2 my-auto showcase-text" >
            <h2>Meaning</h2>
         <!--   <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p> -->
          </div>
        </div>

        
    </section>

    <!-- Testimonials -->
    <section class="testimonials text-center" style="background:black;">
      <div class="container" style="color:white;">
        <h2 class="mb-5">Learn More</h2>
        <div class="row">
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <a href="">  <button type="button" class="btn btn-default btn-lg btn-block">Courses</button></a>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
        <a href=""><button type="button" class="btn btn-default btn-lg btn-block">Forum</button></a>

            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign up now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer" style="background:black;">
      <div class="container">
        <div class="row" >
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto" style="color:white;">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2018. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-twitter fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

categories/templates/business.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="/static/css/landingPageBusiness.css" rel="stylesheet">

  </head>

  <body >

    <!-- Navigation -->
    <div style="background:black;">
    <nav class="navbar navbar-light  static-top" >
      <div class="container">
        <a class="navbar-brand" href="#" style="color:white;">BUSINESS</a>
        <a class="btn btn-primary" href="#">Search</a>
      </div>
    </nav>
  </div>

    <!-- Masthead -->
    <header class="masthead text-white text-center" >
      <div class="overlay"></div>
      <div class="container" style="background-image: url(http://i54.tinypic.com/4zuxif.jpg)">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Know It All Right Here!</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="text" class="form-control form-control-lg" placeholder="Enter your word">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
 <!--   <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Fully Responsive</h3>
              <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
              </div>
              <h3>Bootstrap 4 Ready</h3>
              <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h3>Easy to Use</h3>
              <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
            </div>
          </div>
        </div>
      </div>
    </section> -->

    <!-- Image Showcases -->
    <section class="showcase" style="text-align:center"> 
      <div class="container-fluid p-0">
        <div class="row no-gutters">

       <!--   <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.jpg');"></div> -->
          <div class="col-lg-6 order-lg-2 my-auto showcase-text" >
            <h2>Meaning</h2>
         <!--   <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p> -->
          </div>
        </div>

        
    </section>

    <!-- Testimonials -->
    <section class="testimonials text-center" style="background:black;">
      <div class="container" style="color:white;">
        <h2 class="mb-5">Learn More</h2>
        <div class="row">
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <a href="">  <button type="button" class="btn btn-default btn-lg btn-block">Courses</button></a>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
        <a href=""><button type="button" class="btn btn-default btn-lg btn-block">Forum</button></a>

            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign up now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer" style="background:black;">
      <div class="container">
        <div class="row" >
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto" style="color:white;">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2018. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-twitter fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

categories/templates/computer-science.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="/static/css/landingPageCS.css" rel="stylesheet">

  </head>

  <body >

    <!-- Navigation -->
    <div style="background:black;">
    <nav class="navbar navbar-light  static-top" >
      <div class="container">
        <a class="navbar-brand" href="#" style="color:white;">COMPUTER SCIENCE</a>
        <a class="btn btn-primary" href="#">Search</a>
      </div>
    </nav>
  </div>

    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Know It All Right Here!</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">


                 <form class="form" method="POST" action="/categories/computer-science/search">
				{% csrf_token %}
						<div id="srch">
							<input style="width: 100%;" class="form-control" type="text" name="srch" placeholder="Enter jargon"/>

							</div>
							<br><br>
							<button type="submit" class="button scrolly">Search</button>
</form>




                </div>
                <div class="col-12 col-md-3">

</div>




              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
 <!--   <section class="features-icons bg-light text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Fully Responsive</h3>
              <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
              </div>
              <h3>Bootstrap 4 Ready</h3>
              <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h3>Easy to Use</h3>
              <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
            </div>
          </div>
        </div>
      </div>
    </section> -->

    <!-- Image Showcases -->
    <section class="showcase" style="text-align:center"> 
      <div class="container-fluid p-0">
        <div class="row no-gutters">

       <!--   <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-showcase-1.jpg');"></div> -->
          <div class="col-lg-6 order-lg-2 my-auto showcase-text" >
            <h2>Meaning</h2>
         <!--   <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p> -->
          </div>
        </div>

        
    </section>

    <!-- Testimonials -->
    <section class="testimonials text-center" style="background:black;">
      <div class="container" style="color:white;">
        <h2 class="mb-5">Learn More</h2>
        <div class="row">
          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <a href="">  <button type="button" class="btn btn-default btn-lg btn-block">Courses</button></a>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
        <a href=""><button type="button" class="btn btn-default btn-lg btn-block">Forum</button></a>

            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign up now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer" style="background:black;">
      <div class="container">
        <div class="row" >
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto" style="color:white;">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2018. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fa fa-twitter fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

categories/templates/searcResult.html
<h1>Login</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

<h3>Or <a href="{% url 'sign_in:register' %}">Click Here</a> To Register</h3>

reader/templates/uploadOg.html
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

{% endblock %}